apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsdw.name" . }}
  labels:
    {{- include "rsdw.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rsdw.labels" . | nindent 4 }}
  ports:
    - name: game
      port: {{ .Values.service.port }}
      targetPort: game
      protocol: UDP
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsdw.name" . }}-metrics
  labels:
    {{- include "rsdw.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    {{- include "rsdw.labels" . | nindent 4 }}
  ports:
    - {name: metrics, port: 7979, targetPort: metrics, protocol: TCP}
{{- end }}
