apiVersion: v2
name: rsdragonwilds
description: RuneScape Dragonwilds dedicated server with REST metrics and persistent worlds
type: application
version: 0.2.0
appVersion: "0.2.0"
home: https://github.com/petzkod5/rsdragonwilds-helm
sources:
  - https://github.com/petzkod5/rsdragonwilds-helm
  - https://github.com/runescape/rsdw-dedicated
  - https://github.com/dkoz/RSDWServerAPI
keywords: [dragonwilds, runescape, game-server]
annotations:
  artifacthub.io/license: MIT
